#!/bin/bash

trap "exit" INT TERM

while true; do
    # 12h y 24h
    TIME_12=$(LC_TIME=C date +"%I:%M %p")
    TIME_24=$(date +"%H:%M")
    
    # Fecha completa (Lunes, 18 Enero 2026)
    DATE_FULL=$(date +"%A, %d %B %Y")
    
    # Fecha para la barra (18 Jan 2026)
    DATE_BAR=$(date +"%d %b %Y" | tr -d '.')

    # Enviamos todo en un solo objeto JSON
    printf '{"bar":"%s", "clock":"%s", "date_full":"%s", "date_bar":"%s"}\n' \
           "$TIME_12" "$TIME_24" "$DATE_FULL" "$DATE_BAR"

    # Esperar hasta el segundo 00 del siguiente minuto
    sleep $((60 - 10#$(date +%S)))
done